<?php
declare(strict_types=1);

use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use RubenRomao\DisplayFeaturedProduct\Block\FeaturedProductBlock;
use RubenRomao\DisplayFeaturedProduct\ViewModel\FeaturedProductData;

/** @var Escaper $escaper */
/** @var FeaturedProductBlock $block */
/** @var FeaturedProductData $viewModel */
$viewModel = $block->getData('featured_product_vm');
$productData = $viewModel->getFeaturedProduct();

?>
<?php if ($productData): ?>
    <?php /** @var Product $product */ ?>
    <?php foreach ($productData->getItems() as $product): ?>
        <img class="product base-image"
             src="<?= $escaper->escapeUrl($viewModel->getProductImageUrl($product)) ?>"
             loading="lazy"
             alt="<?= $escaper->escapeHtmlAttr($product->getName()) ?>"
             width="50%"
             height="50%"
        />
    <?php endforeach; ?>
<?php endif; ?>
