<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use RubenRomao\DisplayFeaturedProduct\Block\FeaturedProductBlock;
use RubenRomao\DisplayFeaturedProduct\ViewModel\FeaturedProductData;

/** @var FeaturedProductBlock $block */
/** @var Escaper $escaper */
/** @var FeaturedProductData $productData */
$productData = $block->getData('featured_product_vm');
$data = $productData->getFeaturedProduct();
?>
<div class='left-column'>
    <?php foreach ($data->getItems() as $product): ?>
        <img class="product base-image"
             src="<?= $escaper->escapeUrl($productData->getProductImageUrl($product->getSku())) ?>"
             loading="lazy"
             alt="<?= $escaper->escapeHtmlAttr($product->getName()) ?>"
             width="30%"
             height="30%"
        />
    <?php endforeach; ?>
</div>
