<?php
declare(strict_types=1);

use Magento\Catalog\Block\Product\ListProduct;
use Magento\Framework\Escaper;
use RubenRomao\DisplayFeaturedProduct\Block\FeaturedProductBlock;
use RubenRomao\DisplayFeaturedProduct\ViewModel\FeaturedProductData;

/** @var FeaturedProductBlock $block */
/** @var Escaper $escaper */
/** @var FeaturedProductData $productData */
$productData = $block->getData('featured_product_vm');
$data = $productData->getFeaturedProduct();
/** @var ListProduct $block */
?>
<?php foreach ($data->getItems() as $product): ?>

    <div class='right-column'>
        <div class="product details product-item-details">

            <h2><?= $escaper->escapeHtml($product->getName()) ?></h2>
            <?= $escaper->escapeHtml($product->getData('description')) ?>
            <p><?= $escaper->escapeHtml($product->getData('formated_price')) ?></p>

<!--            --><?php //$productNameStripped = $block->stripTags($product->getName(), null, true); ?>
<!--            <strong class="product name product-item-name">-->
<!--                <a class="product-item-link"-->
<!--                   href="--><?php //= $escaper->escapeUrl($productData->productUrl($product->getSku())) ?><!--">-->
<!--                </a>-->
<!--            </strong>-->

<!--            --><?php //= /* @noEscape */ $block->getProductPrice($product) ?>

<!--            --><?php //= $block->getProductDetailsHtml($product) ?>

        </div>
    </div>
<?php endforeach; ?>
