<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use RubenRomao\DisplayFeaturedProduct\Block\FeaturedProductBlock;
use RubenRomao\DisplayFeaturedProduct\ViewModel\FeaturedProductData;

/** @var FeaturedProductBlock $block */
/** @var Escaper $escaper */
/** @var FeaturedProductData $productData */
$productData = $block->getData('featured_product_vm');
$data = $productData->getFeaturedProduct();
?>
<?php foreach ($data->getItems() as $product): ?>
    <div class="product details product-item-details">
        <h2><?= $escaper->escapeHtml($product->getName()) ?></h2>
        <?= $escaper->escapeHtmlAttr(strip_tags($product->getData('description'))) ?><br/><br>
        <p>
            <strong>
                <label><?= $escaper->escapeHtml(__('Price:')) ?></label>
            </strong>
            <?= $escaper->escapeHtml($productData->getFormattedPrice($product->getData('price'))) ?>
        </p>
        <a href='<?= $escaper->escapeUrl($productData->getProductDetailPageUrl($product->getSku())) ?>'
           class='action primary'>Go to the Product Page
        </a>
    </div>
<?php endforeach; ?>
