<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use RubenRomao\DisplayFeaturedProduct\Block\FeaturedProduct;
use RubenRomao\DisplayFeaturedProduct\ViewModel\FeaturedProductData;

/** @var FeaturedProduct $block */

/** @var Escaper $escaper */

/** @var FeaturedProductData $productData */
$productData = $block->getData('featured_product_vm');
$data = $productData->getFeaturedProduct();

?>
<div class="featured-products">
    <div class="product-image">
        <img src="<?= $escaper->escapeUrl($data['image_url']) ?>"
             alt="<?= $escaper->escapeHtmlAttr($data['name']) ?>">
    </div>
    <div class="product-description">
        <h2><?= $escaper->escapeHtml($data['name']) ?></h2>
        <p><?= $escaper->escapeHtml($data['description']) ?></p>
        <p><?= $escaper->escapeHtml($data['price']) ?></p>
        <button type='button' onclick="location.href='<?= $escaper->escapeUrl($data['product_url']) ?>'"
                class='product-item-inner'>
            <?= $escaper->escapeHtml(__('View Product')) ?>
        </button>
    </div>
</div>
