<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use RubenRomao\DisplayFeaturedProduct\Block\FeaturedProductBlock;
use RubenRomao\DisplayFeaturedProduct\ViewModel\FeaturedProductData;

/** @var FeaturedProductBlock $block */
/** @var Escaper $escaper */
/** @var FeaturedProductData $productData */
$productData = $block->getData('featured_product_vm');
$data = $productData->getFeaturedProduct();
?>
<?php foreach ($data->getItems() as $product): ?>
    <div class="product details product-item-details">
        <h2><?= $escaper->escapeHtml($product->getName()) ?></h2>
        <?= $escaper->escapeHtml($product->getData('description')) ?>
        <p><?= $escaper->escapeHtml($product->getData('formated_price')) ?></p>
        <!-- Button to send the customer to the product page -->
        <!-- Link styled as a button to send the customer to the product page -->
        <a href="<?= $escaper->escapeUrl($productData->getProductDetailPageUrl($product->getSku())) ?>" class='button'>
            <?= $escaper->escapeHtml(__('Go To The Product Page')) ?>
        </a>
    </div>
<?php endforeach; ?>
