<?php
declare(strict_types=1);

use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use RubenRomao\DisplayFeaturedProduct\Block\FeaturedProductBlock;
use RubenRomao\DisplayFeaturedProduct\ViewModel\FeaturedProductData;

/** @var Escaper $escaper */
/** @var FeaturedProductBlock $block */
/** @var FeaturedProductData $viewModel */
$viewModel = $block->getData('featured_product_vm');
$productData = $viewModel->getFeaturedProduct();

// phpcs:disable Generic.Files.LineLength
?>
<?php if ($productData): ?>
    <?php /** @var Product $product */ ?>
    <?php foreach ($productData->getItems() as $product): ?>
        <section class="text-gray-700 body-font flex relative z-10">
            <div class="container mx-auto flex px-5 mt-8 xl:-mt-12 md:flex-row flex-col items-center">
                <div class="w-full xl:w-1/2 md:w-1/3 sm:w-5/6 mb-10 md:mb-0">
                    <img class="object-cover object-center rounded shadow-lg rounded-md"
                         src="<?= $escaper->escapeHtmlAttr($viewModel->getProductImageUrl($product)) ?>"
                         alt=""
                         width="500"
                         height="500"
                         loading="lazy"
                         aria-hidden="true"
                    >
                </div>
                <div
                    class="xl:grow md:w-2/3 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
                    <h2 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                        <?= $escaper->escapeHtml($product->getName()) ?></h2>
                    <p class="mb-8 leading-relaxed">
                        <?= $escaper->escapeHtmlAttr(strip_tags($product->getDescription())) ?>
                    </p>
                    <p class="text-xl">
                        <?= $escaper->escapeHtml(__('Price: ')) ?>
                        <?= $escaper->escapeHtml(strip_tags((string)$product->getFormattedPrice())) ?>
                    </p>
                    <div class="flex justify-center">
                        <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                           class="inline-flex btn btn-primary">
                            <?= $escaper->escapeHtml(__('Go to the Product Page')) ?>
                        </a>
                    </div>
                </div>
            </div>
        </section>
    <?php endforeach; ?>
<?php endif; ?>
